### ISSUE TITLE
Suggestion: Maybe moving to a vanilla like command syntax 

### ISSUE THREAD

**Issue by macbrayne** [Pepe20129/difficultytweaker#2]
Maybe something like /difficultyTweaker entity and /difficultyTweaker environment localDifficulty or something similar.
The benefit of it is of course highly subjective, just something I wanted to propose!

**Comment by Pepe20129** [comment]
That is a very good idea and pretty simple to implement so I'll probably include it in 0.1.3

**Comment by macbrayne** [comment]
I also saw your config format is a bit barebones. You could move to using Gson or toml4j for Object Mapping (which is much nicer than manual `config.get("key")`.

**Comment by Pepe20129** [comment]
Closed with 0.2.1
