### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by macbrayne** [Pepe20129/difficultytweaker#3]
Do you want to keep it ARR or move to a open-source license?
For a Minecraft mod you could use the LGLPv3, MIT or Apache 2: https://choosealicense.com/

Unfortunately you can't really use GLPv3 as there are [issues](https://github.com/modrinth/code/issues/1992) with its use in Minecraft mods.

**Comment by Pepe20129** [comment]
Oops, I forgot to set it in GitHub. It's in the `fabric.mod.json` as LGPLv3. I'll set it also on GitHub.
