### ISSUE TITLE
Crashed on startup 0.2.5

### ISSUE THREAD

**Issue by LostChairr** [Pepe20129/difficultytweaker#8]
26.04 23:26:54 [Server] main/INFO Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
26.04 23:26:54 [Server] main/INFO Loading 145 mods:
26.04 23:26:54 [Server] INFO - adorn 3.3.1+1.18.1
26.04 23:26:54 [Server] INFO - adventurez 1.4.9
26.04 23:26:54 [Server] INFO - alternate-current 1.2.0
26.04 23:26:54 [Server] INFO - amplified_nether 1.0.1
26.04 23:26:54 [Server] INFO - antishulkerdupe 1.0.0
26.04 23:26:54 [Server] INFO - arcanus 1.27
26.04 23:26:54 [Server] INFO - artifacts 6.0.0+fabric
26.04 23:26:54 [Server] INFO - backslot 1.2.5
26.04 23:26:54 [Server] INFO - bedbenefitsfabric 1.18-0.1.0
26.04 23:26:54 [Server] INFO - bedspreads 1.5.0-1.18
26.04 23:26:54 [Server] INFO - bountiful 2.0.1
26.04 23:26:54 [Server] INFO - c2me 0.2.0+alpha.6.55
26.04 23:26:54 [Server] INFO - cardinal-components-base 4.1.3 via puzzleslib
26.04 23:26:54 [Server] INFO - cardinal-components-entity 4.1.3 via puzzleslib
26.04 23:26:54 [Server] INFO - carpet 1.4.57
26.04 23:26:54 [Server] INFO - cavetweaks 1.0
26.04 23:26:54 [Server] INFO - chipped 1.2
26.04 23:26:54 [Server] INFO - chunky 1.2.164
26.04 23:26:54 [Server] INFO - cloth-basic-math 0.6.0 via cloth-config
26.04 23:26:54 [Server] INFO - cloth-config 6.1.50 via cavetweaks
26.04 23:26:54 [Server] INFO - cloth-config-lite 2.0.6 via omega-config-gui
26.04 23:26:54 [Server] INFO - clumps 8.0.0+7
26.04 23:26:54 [Server] INFO - com_electronwill_night-config_core 3.6.5 via servercore
26.04 23:26:54 [Server] INFO - com_electronwill_night-config_toml 3.6.5 via servercore
26.04 23:26:54 [Server] INFO - com_eliotlash_mclib_mclib 18 via geckolib3
26.04 23:26:54 [Server] INFO - com_eliotlash_molang_molang 18 via geckolib3
26.04 23:26:54 [Server] INFO - com_ishland_c2me_libs_ 0.2.0+alpha.6.55 via c2me
26.04 23:26:54 [Server] INFO - com_moandjiezana_toml_toml4j 0.7.2 via servertick
26.04 23:26:54 [Server] INFO - com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
26.04 23:26:54 [Server] INFO - comforts 1.0.3-1.18.1
26.04 23:26:54 [Server] INFO - config2brigadier 1.0.2 via healthcare
26.04 23:26:54 [Server] INFO - craftable_enchanted_golden_apple 1.0.2
26.04 23:26:54 [Server] INFO - dataattributes 1.1.5
26.04 23:26:54 [Server] INFO - difficultytweaker 0.2.5+1.18
26.04 23:26:54 [Server] INFO - dragonloot 1.0.10
26.04 23:26:54 [Server] INFO - drinkbeer 3.0.2
26.04 23:26:54 [Server] INFO - eldritch_mobs 1.10.4
26.04 23:26:54 [Server] INFO - enhancedcelestials 2.0.6
26.04 23:26:54 [Server] INFO - expandability 5.0.0 via artifacts
26.04 23:26:56 [Multicraft] Skipped 119 lines due to rate limit (40/s)
26.04 23:26:56 [Server] main/WARN Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
26.04 23:26:56 [Server] main/WARN @Mixin target net.minecraft.class_906 was not found go-fish.mixins.json:FishingBobberEntityRendererMixin
26.04 23:26:56 [Server] main/WARN Error loading class: net/minecraft/class_702 (java.lang.ClassNotFoundException: net/minecraft/class_702)
26.04 23:26:56 [Server] main/WARN @Mixin target net.minecraft.class_702 was not found go-fish.mixins.json:ParticleManagerMixin
26.04 23:26:56 [Server] main/WARN Error loading class: net/minecraft/class_998 (java.lang.ClassNotFoundException: net/minecraft/class_998)
26.04 23:26:56 [Server] main/WARN @Mixin target net.minecraft.class_998 was not found impaled.mixins.json:TridentRiptideFeatureRendererMixin
26.04 23:26:56 [Server] main/WARN Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
26.04 23:26:56 [Server] main/WARN Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
26.04 23:26:56 [Server] main/WARN Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton]) disables it and children
26.04 23:26:56 [Server] main/WARN Error loading class: net/minecraft/class_310 (java.lang.ClassNotFoundException: net/minecraft/class_310)
26.04 23:26:56 [Server] main/WARN @Mixin target net.minecraft.class_310 was not found ostOverhaul.mixins.json:MinecraftClientMixin
26.04 23:26:56 [Server] main/WARN Error loading class: net/minecraft/class_1142 (java.lang.ClassNotFoundException: net/minecraft/class_1142)
26.04 23:26:56 [Server] main/WARN @Mixin target net.minecraft.class_1142 was not found ostOverhaul.mixins.json:MusicTrackerMixin
26.04 23:26:56 [Server] main/INFO Adding mixins: [None]
26.04 23:26:57 [Server] main/INFO Kambrik Says Hello!
26.04 23:26:58 [Server] main/INFO Smooth Boot config initialized
26.04 23:26:59 [Server] main/INFO Checking for STORE & LOAD on var 1 within net/minecraft/class_2622.method_39026(Lnet/minecraft/class_2586;Ljava/util/function/Function;)Lnet/minecraft/class_2622; in net/minecraft/class_3222.method_7323(Lnet/minecraft/class_2593;)V
26.04 23:26:59 [Server] main/INFO Redirecting net/minecraft/class_2622.method_39026(Lnet/minecraft/class_2586;Ljava/util/function/Function;)Lnet/minecraft/class_2622;
26.04 23:26:59 [Server] main/WARN Cannot redirect var 1 in net/minecraft/class_3222.method_7323(Lnet/minecraft/class_2593;)V as it is purely a parameter.
26.04 23:27:01 [Server] main/INFO Redirected net/minecraft/class_1937.method_8320(Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; in net/minecraft/class_1540.method_5773()V to plymouth$getShadowBlock for net/minecraft/class_2626.<init>(Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)V
26.04 23:27:01 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2587.method_38237()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:01 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2636.method_38251()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:01 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2625.method_38249()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:01 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2580.method_38236()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:01 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2631.method_38250()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:02 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2573.method_16886()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:02 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2643.method_38253()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:02 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2597.method_38247()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:02 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_3924.method_38245()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:02 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_2633.method_38252()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:02 [Server] main/WARN This reference for net/minecraft/class_2622.method_38585(Lnet/minecraft/class_2586;)Lnet/minecraft/class_2622; in net/minecraft/class_3751.method_38248()Lnet/minecraft/class_2622;, ignoring
26.04 23:27:03 [Server] main/WARN @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$bhk000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
26.04 23:27:04 [Server] main/ERROR Mixin apply for mod carpet failed carpet.mixins.json:ProjectileEntity_extremeMixin -> net.minecraft.class_1665: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1665::nextGauBian2 with priority 1000 cannot inject into net/minecraft/class_1665::method_7435(Lnet/minecraft/class_1309;F)V merged by io.github.pepe20129.difficultytweaker.mixin.PersistentProjectileEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ProjectileEntity_extremeMixin -> Prepare Injections ->  -> redirect$baa000$nextGauBian2(Ljava/util/Random;)D -> Prepare]
26.04 23:27:04 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1665::nextGauBian2 with priority 1000 cannot inject into net/minecraft/class_1665::method_7435(Lnet/minecraft/class_1309;F)V merged by io.github.pepe20129.difficultytweaker.mixin.PersistentProjectileEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ProjectileEntity_extremeMixin -> Prepare Injections ->  -> redirect$baa000$nextGauBian2(Ljava/util/Random;)D -> Prepare]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
26.04 23:27:04 [Server] INFO at net.gudenau.minecraft.asm.impl.MixinTransformer.lambda$transformClassBytes$3(Unknown Source) ~[?:?]
26.04 23:27:04 [Server] INFO at net.gudenau.minecraft.asm.impl.MixinTransformer.cache(Unknown Source) ~[?:?]
26.04 23:27:04 [Server] INFO at net.gudenau.minecraft.asm.impl.MixinTransformer.transformClassBytes(Unknown Source) ~[?:?]
26.04 23:27:04 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
26.04 23:27:04 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
26.04 23:27:04 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
26.04 23:27:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
26.04 23:27:04 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
26.04 23:27:04 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
26.04 23:27:04 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
26.04 23:27:04 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
26.04 23:27:04 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
26.04 23:27:04 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
26.04 23:27:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_1299.<clinit>(class_1299.java:163) ~[server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_5458.<clinit>(class_5458.java:77) [server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_2378.<clinit>(class_2378.java:269) [server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:49) [server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
26.04 23:27:04 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
26.04 23:27:04 [Multicraft] Server shut down (starting)
26.04 23:27:04 [Multicraft] Restarting crashed server in 600.0 seconds
26.04 23:27:04 [Multicraft] Stopping server!
26.04 23:27:06 [Multicraft] Looks like a crash, check the server console. Return value: 1
26.04 23:27:06 [Multicraft] Server stopped
26.04 23:27:10 [Multicraft] Loading server properties

**Comment by Pepe20129** [comment]
This mod is currently incompatible with the carpet mod.
It's 100% my fault, I'll try to fix it, but I can't promise anything.

**Comment by Pepe20129** [comment]
Fixed in 0.2.6
